Side dist
UbiquityRobotics/move_basic pull request #46
Opened 2019-04-13 21:21 UTC by jim-v

Implements a side following mode.
Fixes some wierdness when operating in the map frame

2019-04-13 21:28 UTC, jim-v commented
Run with UbiquityRobotics/move_basic#86

2019-04-15 14:42 UTC, rohbotics requested changes

2019-04-15 14:42 UTC, rohbotics commented on src/map.cpp
> +/*
I think this is a mistake.

Unless there has been a major architecture change :)

2019-04-15 14:42 UTC, rohbotics commented on README.md
> +## New obstacle avoidance behavoir (March 2019)
Can you describe the new behavior here

2019-04-15 14:42 UTC, rohbotics commented on include/move_basic/obstacle_detector.h
> +   //TODO: refactor
This todo needs to either be done, or more detailed

2019-04-15 14:42 UTC, rohbotics commented on src/move_basic.cpp
> +#include <std_msgs/UInt8.h>
Should be custom msg type with 'enum' in it. 

Something like
```
uint8 DRIVE_STRAIGHT=0
uint8 FOLLOW_LEFT=1
uint8 FOLLOW_RIGHT=2

uint8 state
```

2019-04-15 14:42 UTC, rohbotics commented on src/move_basic.cpp
> +    // XXX bogus rotation to test linear recovery
This is icky, but we can keep it for now

2019-04-15 14:42 UTC, rohbotics commented on src/move_basic.cpp
> +        if (followMode == FOLLOW_LEFT) {
Switch statement here? (Doesn't need branches)

2019-04-15 14:42 UTC, rohbotics commented on src/move_basic.cpp
> +        // TODO: is this the best test of completeness?
No, this is not a great test of completeness. I think the robot should still aim for the x position, not x-tolerance. This should be added as an issue

2019-04-15 16:01 UTC, jim-v commented on src/map.cpp
> +/*
Yes, removed.

2019-04-17 06:54 UTC, jim-v commented on include/move_basic/obstacle_detector.h
> +   //TODO: refactor
Removed the comment.

2019-04-17 07:02 UTC, jim-v commented on src/move_basic.cpp
> +        if (followMode == FOLLOW_LEFT) {
I can see advantages and disadvantages of both.  `if ... else if` gives a new scope and there is no danger of falling through to the wrong block if a `break` statement is missing.

2019-04-18 08:04 UTC, jim-v commented on README.md
> +## New obstacle avoidance behavoir (March 2019)
Done

2019-04-18 08:04 UTC, jim-v commented
@rohbotics, this is ready to be reviewed again when you have time.

2019-05-03 02:36 UTC, rohbotics commented
Hey Jim, let me know when you want me to re-review this.

2019-05-03 04:46 UTC, jim-v commented
> Hey Jim, let me know when you want me to re-review this.

I'm going to spend some time at the weekend seeing if I can make it work better, but it would be good if you take a look at it before that (assuming you have time), to see if you can spot any potential issues.

2019-05-04 00:58 UTC, rohbotics commented
I took a look at it, nothing really stands out as a problem.

There is a lot of close to repetitive code, especially in obstacle detector, with subtle differences. 
If it is easy to parametrize the differences, instead of mostly repeating, that would be nice, but not needed.

2019-05-23 23:14 UTC, rohbotics approved these changes
I think we can merge this. Nothing seems obviously wrong, and if we find some quality problems later on we can fix them.

2019-05-25 01:20 UTC, merged