Smooth turning towards new goal
UbiquityRobotics/move_basic pull request #50
Opened 2020-03-12 13:16 UTC by MoffKalast

Added parameter toggleable smooth cornering as seen [here](https://drive.google.com/file/d/13ho4MqTTbJDcw6dd5NiNO5tKzmKEnl5f/view).

Upon receiving a new goal the linear velocity is preserved for a short time to prevent sudden stops at high speed that degrade wheel gears and spill cargo. Theoretically it should reduce accuracy a bit, though I haven't observed anything drastic during testing so far. It's safe to say that I haven't covered even close to all edge cases though.

It should stop once an obstacle is found during the time of slowdown, however I don't have a sonar board on hand to test that part out.

2020-03-12 14:22 UTC, rohbotics requested changes
Before reviewing the code itself, I have some concerns over the algorithm itself.

If I understand correctly, the idea is that if the robot is moving in a straight line and gets a new goal, instead of stopping and turning, it executes a smooth turn between the current heading and the new heading.

This sounds like it would work out well for smaller angle changes (<90 degrees), but smooth turning should not be attempted for larger angles. If I want the robot to turn around, continuing to go forward while doing so would be incorrect. A parameter for a maximum angle is probably a good idea.

Also this is using the forward obstacle distance, which assumes the robot is going in a straight line, but the robot will actually be going along a curve. We need to extend the obstacle distance function to be able to calculate along the curve, or else you could have problems when the robot is near a wall. Maybe change this to an obstacle time function that can find the time to the nearest obstacle given a linear and angular velocity? This problem requires some more thought.


Let me know if you have any questions.

2020-03-12 14:25 UTC, rohbotics commented
@MoffKalast thanks for the PR and review request. As a procedural note, the assignee should be the person that is currently working on the PR, generally not the reviewers. This way it is easy to see who the PR belongs to on the projects board.

2020-03-12 14:44 UTC, MoffKalast commented
> If I want the robot to turn around, continuing to go forward while doing so would be incorrect.

Well yes, but actually no. The robot should indeed stop, but not instantly since that results in a very intensive braking manever that can supposedly harm the motor's plastic gears - and also spill potential cargo. This should bring the robot to a stop during the rotation phase. The entire idea is to make all movement smoother at the expense of exact positioning.

Then again I haven't really tested what exactly happens if it tries to turn 180 at max speed, so I'll definitely attempt that when I get the chance.

> We need to extend the obstacle distance function to be able to calculate along the curve, or else you could have problems when the robot is near a wall.

Hmm, fair point. The rotation system already has an obstacle check for left and right though and it's also operating at the time, though it only influences rotation. That could end up working fine if the robot finds a wall and simply stops rotating to avoid it, the question is if the forward sonar will even pick up the wall in such an orientation.

And it's not like we can do much in terms of advanced curve planning when we only have sonars of questionable reliability only every 45 degrees.

Anyhow, it needs to be tested with an actual sonar board before we can say anything.

>  the assignee should be the person that is currently working on the PR, generally not the reviewers

Right, fixed. I was not entirely sure if simply assigning people would send any notifications.

2020-03-15 20:38 UTC, rohbotics commented
The move_basic obstacle detector also supports Lidar and possibly the ToF system. Obviously the sonars are significantly lower quality data sources, but we should still attempt to be correct.

Maybe an interim solution for all this is just smoothly decelerating to a stop _before_ we start turning, and calculate the turning angle only after we stop.

2020-03-15 21:04 UTC, MoffKalast commented
I'll try to look into that when possible. Thing is, stopping at a goal should be optional since it very much isn't desired behaviour if you want to continuously follow goals to maximize overall travel speed.

What I've done for now regarding angle based cornering is adding two parameters - min and max corner braking values that scale braking power depending on the sharpness of the angle. That way it's possible to not brake at all at very shallow angles and stop completely at wide ones, which seems to work fine for now. Testing at high speed and giving it a goal at 180 degrees would make it veer off quite severely with the previous setup of one general parameter.

2020-07-09 19:03 UTC, closed without merging